Repository spacetelescope/webbpsf, pull requests merged in 2021-01, with the labels that each got.

#395 update syntax to remove unnecessary underscores after poppy PR 386
  webbpsf/tests/test_nircam.py
  webbpsf/tests/test_webbpsf.py
  webbpsf/tests/test_wfirst.py
  webbpsf/tests/validate_webbpsf.py
  webbpsf/webbpsf_core.py
  webbpsf/wfirst.py
Labels: bug

#396 update opd thermal slew test, in particular for a change in pupil segment data file
  webbpsf/opds.py
  webbpsf/tests/test_opds.py
Labels: data_files, testing

#400 WebbPSF: Rename WFIRST -> Roman
  docs/README figure.ipynb
  docs/_themes/theme_webbpsf/layout.html
  docs/index.rst
  docs/intro.rst
  docs/readme_fig.png
  docs/roman.rst
  docs/roman_figures/compare_wfi_sca09_sca17.png
  docs/roman_figures/field_layout.png
  docs/roman_figures/field_layout_cycle6.png
  docs/roman_figures/fig_cgi_spc_f770.png
  docs/roman_figures/pupil_mask_by_sca.gif
  docs/roman_figures/webbpsf-roman_page_header.png
  docs/usage.rst
  notebooks/WebbPSF-Roman_Tutorial.ipynb
  notebooks/WebbPSF-WFIRST_Tutorial.ipynb
  notebooks/roman_cgi_demo.ipynb
  notebooks/wfirst_cgi_demo.ipynb
  webbpsf/__init__.py
  webbpsf/jupyter_gui.py
  webbpsf/roman.py
  webbpsf/tests/test_psfgrid.py
  webbpsf/tests/test_roman.py
Labels: Roman, docs
