Repository spacetelescope/webbpsf, pull requests merged in 2024-05, with the labels that each got.

#787 improve MIRI LRS model details
  webbpsf/detectors.py
  webbpsf/tests/test_miri.py
  webbpsf/webbpsf_core.py
Labels: enhancement, JWST

#834 avoid linear interpolation between WFE values
  webbpsf/trending.py
Labels: bug

#848 Update for WFI to use pysiaf instead of soc_roman_tools
  pyproject.toml
  webbpsf/distortion.py
Labels: dependencies

#837 Improved model for MIRI cruciform artifact, part 1
  docs/relnotes.rst
  webbpsf/constants.py
  webbpsf/detectors.py
  webbpsf/tests/test_detectors.py
Labels: enhancement, JWST

#845 Implement support for NIRCam DHS sub apertures
  webbpsf/webbpsf_core.py
Labels: priority:high, data_files, JWST

#850 Couple small fixes to LRS support
  webbpsf/match_data.py
  webbpsf/tests/test_miri.py
  webbpsf/webbpsf_core.py
Labels: bug, JWST
