Repository spacetelescope/webbpsf, pull requests merged in 2024-12, with the labels that each got.

#936 Minor update to docs about the WFI optical model
  README.rst
  docs/roman.rst
Labels: docs

#943 update monthly trending plot to allow shifted date ranges
  webbpsf/trending.py
Labels: enhancement, JWST

#945 update MAST query for OPDs to also retrieve OPDs from FP6
  webbpsf/mast_wss.py
  webbpsf/webbpsf_core.py
Labels: bug, enhancement, JWST
